framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: warn #esto hay que ponerlo si no no funciona el apiplatform, no se muestra

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
