parameters:
    openai.api_key: '%env(OPENAI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $openAiApiKey: '%openai.api_key%'

    App\Controller\ChatController:
        arguments:
            $openAiApiKey: '%openai.api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
